version: '3.7'

services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - postgres
    environment:
      BOT_PUBLIC_PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: qwer1234
      POSTGRES_DB: qwer1234

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: qwer1234
      POSTGRES_DB: qwer1234

volumes:
  postgres-data: